/*
Blockdaemon DeFi API

The Blockdaemon DeFi API provides a single interface to a multitude of DeFi projects and blockchains

API version: 1.0.0
Contact: info@blockdaemon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Routes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Routes{}

// Routes A collection of available routes for swapping tokens.
type Routes struct {
}

// NewRoutes instantiates a new Routes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutes() *Routes {
	this := Routes{}
	return &this
}

// NewRoutesWithDefaults instantiates a new Routes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutesWithDefaults() *Routes {
	this := Routes{}
	return &this
}

func (o Routes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Routes) ToMap() (map[string]interface{}, error) {
	toSerialize := make([]interface{}, len(o.Items))
	for i, item := range o.Items {
		toSerialize[i] = item
	}
	return toSerialize, nil
}

func (o *Routes) UnmarshalJSON(data []byte) (err error) {
	return json.Unmarshal(data, &o.Items)
}

type NullableRoutes struct {
	value Routes
	isSet bool
}

func (v NullableRoutes) Get() Routes {
	return v.value
}

func (v *NullableRoutes) Set(val Routes) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutes) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutes(val Routes) *NullableRoutes {
	return &NullableRoutes{value: val, isSet: true}
}

func (v NullableRoutes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


