/*
Blockdaemon DeFi API

The Blockdaemon DeFi API provides a single interface to a multitude of DeFi projects and blockchains

API version: 1.0.0
Contact: info@blockdaemon.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenApprovalDeletion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenApprovalDeletion{}

// TokenApprovalDeletion The address of an account.
type TokenApprovalDeletion struct {
	// The unique identifier of a blockchain in CAIP-2 notation.
	ChainID string `json:"chainID" validate:"regexp=^[-a-z0-9]{3,8}:[-_a-zA-Z0-9]{1,32}$"`
	// The address of an account.
	AccountAddress string `json:"accountAddress"`
	// The address of an account.
	SpenderAddress string `json:"spenderAddress"`
	// The address of an account.
	TokenAddress string `json:"tokenAddress"`
}

type _TokenApprovalDeletion TokenApprovalDeletion

// NewTokenApprovalDeletion instantiates a new TokenApprovalDeletion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenApprovalDeletion(chainID string, accountAddress string, spenderAddress string, tokenAddress string) *TokenApprovalDeletion {
	this := TokenApprovalDeletion{}
	this.ChainID = chainID
	this.AccountAddress = accountAddress
	this.SpenderAddress = spenderAddress
	this.TokenAddress = tokenAddress
	return &this
}

// NewTokenApprovalDeletionWithDefaults instantiates a new TokenApprovalDeletion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenApprovalDeletionWithDefaults() *TokenApprovalDeletion {
	this := TokenApprovalDeletion{}
	return &this
}

// GetChainID returns the ChainID field value
func (o *TokenApprovalDeletion) GetChainID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainID
}

// GetChainIDOk returns a tuple with the ChainID field value
// and a boolean to check if the value has been set.
func (o *TokenApprovalDeletion) GetChainIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainID, true
}

// SetChainID sets field value
func (o *TokenApprovalDeletion) SetChainID(v string) {
	o.ChainID = v
}

// GetAccountAddress returns the AccountAddress field value
func (o *TokenApprovalDeletion) GetAccountAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountAddress
}

// GetAccountAddressOk returns a tuple with the AccountAddress field value
// and a boolean to check if the value has been set.
func (o *TokenApprovalDeletion) GetAccountAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountAddress, true
}

// SetAccountAddress sets field value
func (o *TokenApprovalDeletion) SetAccountAddress(v string) {
	o.AccountAddress = v
}

// GetSpenderAddress returns the SpenderAddress field value
func (o *TokenApprovalDeletion) GetSpenderAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpenderAddress
}

// GetSpenderAddressOk returns a tuple with the SpenderAddress field value
// and a boolean to check if the value has been set.
func (o *TokenApprovalDeletion) GetSpenderAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpenderAddress, true
}

// SetSpenderAddress sets field value
func (o *TokenApprovalDeletion) SetSpenderAddress(v string) {
	o.SpenderAddress = v
}

// GetTokenAddress returns the TokenAddress field value
func (o *TokenApprovalDeletion) GetTokenAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAddress
}

// GetTokenAddressOk returns a tuple with the TokenAddress field value
// and a boolean to check if the value has been set.
func (o *TokenApprovalDeletion) GetTokenAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenAddress, true
}

// SetTokenAddress sets field value
func (o *TokenApprovalDeletion) SetTokenAddress(v string) {
	o.TokenAddress = v
}

func (o TokenApprovalDeletion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenApprovalDeletion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chainID"] = o.ChainID
	toSerialize["accountAddress"] = o.AccountAddress
	toSerialize["spenderAddress"] = o.SpenderAddress
	toSerialize["tokenAddress"] = o.TokenAddress
	return toSerialize, nil
}

func (o *TokenApprovalDeletion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chainID",
		"accountAddress",
		"spenderAddress",
		"tokenAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenApprovalDeletion := _TokenApprovalDeletion{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenApprovalDeletion)

	if err != nil {
		return err
	}

	*o = TokenApprovalDeletion(varTokenApprovalDeletion)

	return err
}

type NullableTokenApprovalDeletion struct {
	value *TokenApprovalDeletion
	isSet bool
}

func (v NullableTokenApprovalDeletion) Get() *TokenApprovalDeletion {
	return v.value
}

func (v *NullableTokenApprovalDeletion) Set(val *TokenApprovalDeletion) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenApprovalDeletion) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenApprovalDeletion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenApprovalDeletion(val *TokenApprovalDeletion) *NullableTokenApprovalDeletion {
	return &NullableTokenApprovalDeletion{value: val, isSet: true}
}

func (v NullableTokenApprovalDeletion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenApprovalDeletion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


